#!/usr/bin/env bash
#
# Simple continuous integration script for a Go project
#

set -e

echo "* Golint code style check"
find -name "*.go" | xargs -i golint '{}'
echo

echo "* Go vet code health check"
find -name "*.go" | xargs -i go tool vet '{}'
echo

echo "* Build Go application"
go build
echo

echo "[ Specs ]"
go test
echo

if [ ! ${SKIP_XCOMPILE} ]; then
  echo "[ X-Compile ]"
  ./script/xcompile
  echo
fi
