#!/usr/bin/env bash
#
# Install project components
#
echo "Installing dependencies..."

# Linter for Go source code
go get -u -t github.com/golang/lint/golint

# 3rd-party Go packages used in project
go get -u -t \
  errors \
	flag \
	fmt \
	golang.org/x/crypto/ssh \
	golang.org/x/crypto/ssh/agent \
	gopkg.in/yaml.v2 \
	io \
	io/ioutil \
	log \
	math/rand \
	net \
	net/http \
	os os/user \
	regexp \
	strconv \
	strings \
	testing \
	time

# My sshtunnel package
go get -u -t github.com/ivanilves/gopack/sshtunnel
