#!/bin/bash

NAME=ptu

for GOOS in darwin linux windows; do
  for GOARCH in 386 amd64; do
    BINARY_NAME=${NAME}-${GOOS}-${GOARCH}
    echo "* Building ${BINARY_NAME}"
    export GOOS=${GOOS}
    export GOARCH=${GOARCH}
    go build -o bin/${BINARY_NAME}
  done
done
