#!/bin/bash

NAME=ptu

for GOOS in darwin linux windows; do
  for GOARCH in 386 amd64; do
    if [ ${GOOS} != "windows" ]; then
      BINARY_NAME=${NAME}-${GOOS}-${GOARCH}
    else
      BINARY_NAME=${NAME}-${GOOS}-${GOARCH}.exe
    fi

    echo "* Building ${BINARY_NAME}"
    export GOOS=${GOOS}
    export GOARCH=${GOARCH}
    go build -o bin/${BINARY_NAME}
  done
done
